/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

import java.awt.HeadlessException;
import java.math.BigInteger;
import java.util.Scanner;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JOptionPane;
import static simulador.Cuadrados_Medios_1.buscar;

/**
 *
 * @author Administrator
 */
public class SimuladorFunciones extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorFunciones
     */
    public SimuladorFunciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIteraciones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtG = new javax.swing.JTextField();
        btGenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIteracionesMedios = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtX_GCL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIteraciones_GCL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtM = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(2, 4));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Semilla");
        jPanel4.add(jLabel1);

        txtX.setText("1");
        txtX.setToolTipText("");
        jPanel4.add(txtX);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("N° Iteraciones");
        jPanel4.add(jLabel2);

        txtIteraciones.setText("5");
        txtIteraciones.setToolTipText("");
        jPanel4.add(txtIteraciones);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("f(x)=");
        jPanel4.add(jLabel3);

        txtF.setText("(x+2)/x^2");
        txtF.setToolTipText("");
        jPanel4.add(txtF);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("g(x)=");
        jPanel4.add(jLabel4);

        txtG.setText("x*33");
        txtG.setToolTipText("");
        jPanel4.add(txtG);

        btGenerar.setText("Generar");
        btGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btGenerar)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Basico", jPanel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Semilla");
        jPanel5.add(jLabel5);

        txtNumero.setText("1234");
        txtNumero.setToolTipText("");
        jPanel5.add(txtNumero);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("N° Iteraciones");
        jPanel5.add(jLabel6);

        txtIteracionesMedios.setText("5");
        txtIteracionesMedios.setToolTipText("");
        jPanel5.add(txtIteracionesMedios);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Medios", null, jPanel2, "");

        jPanel6.setLayout(new java.awt.GridLayout(3, 4));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Semilla");
        jPanel6.add(jLabel7);

        txtX_GCL.setText("1");
        txtX_GCL.setToolTipText("");
        jPanel6.add(txtX_GCL);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("N° Iteraciones");
        jPanel6.add(jLabel8);

        txtIteraciones_GCL.setText("5");
        txtIteraciones_GCL.setToolTipText("");
        jPanel6.add(txtIteraciones_GCL);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("a");
        jPanel6.add(jLabel9);

        txtA.setText("7");
        txtA.setToolTipText("");
        jPanel6.add(txtA);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("b");
        jPanel6.add(jLabel10);

        txtB.setText("5");
        txtB.setToolTipText("");
        jPanel6.add(txtB);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("m");
        jPanel6.add(jLabel11);

        txtM.setText("101");
        txtM.setToolTipText("");
        jPanel6.add(txtM);

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("GCL", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarActionPerformed
        // TODO add your handling code here:
        int semilla, iteraciones;
        String funcionF, funcionG;

        try {
            semilla = Integer.parseInt(txtX.getText());
            iteraciones = Integer.parseInt(txtIteraciones.getText());
            funcionF = txtF.getText().toLowerCase();
            funcionG = txtG.getText().toLowerCase();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Datos ingresador invalidos.\n intente nuevamente.");
            return;
        }

        double fx = ejecutarFuncion(semilla, funcionF, iteraciones);

        JOptionPane.showMessageDialog(rootPane, String.format("f(x)=%.2f", fx));

        double gx = ejecutarFuncion(semilla, funcionG, iteraciones);

        JOptionPane.showMessageDialog(rootPane, String.format("g(x)=%.2f", gx));
        //JOptionPane.showMessageDialog(rootPane, String.format("f(x)=%.2f\ng(x)=%.2f", fx,gx));


    }//GEN-LAST:event_btGenerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        BigInteger n = new BigInteger(txtNumero.getText());

        System.out.println("Introdusca la cantidad que quiere generar X0");
        int r = Integer.parseInt(txtIteracionesMedios.getText());
        int aux = 0, digito = String.valueOf(n).length();
        for (int i = 0; i < r; i++) {
            aux = buscar(n.multiply(n).toString(), digito);
            JOptionPane.showMessageDialog(rootPane, "0." + aux);
            n = BigInteger.valueOf(aux);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int a, b, m, x, n;

        try {
            a = Integer.parseInt(txtA.getText());
            b = Integer.parseInt(txtB.getText());
            m = Integer.parseInt(txtM.getText());
            x = Integer.parseInt(txtX_GCL.getText());
            n = Integer.parseInt(txtIteraciones_GCL.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "valores ingresados invalidos.");
            return;
        }

        for (int i = 0; i < n; i++) {
            x = ((a * x) + b) % m;
            double aleatorio = (double) x / m;
            System.out.println(aleatorio);

            JOptionPane.showMessageDialog(rootPane, aleatorio);

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private double ejecutarFuncion(int semilla, String funcion, int iteraciones) throws HeadlessException {
        double x = semilla;
        //quita cualquier espacion en la funcion
        funcion = funcion.replace("\\s+", "");
        //utiliza libreria JAVASCRIPT para ejecutar las operaciones
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine engine = mgr.getEngineByName("JavaScript");

        try {

            for (int i = 0; i < iteraciones; i++) {

                String temp = funcion.replace("x", String.format("%.2f", x));
                System.out.print("funcion = " + temp + " = ");

                //busca potencias
                while (temp.indexOf("^") != -1) {
                    int index = temp.indexOf("^");
                    String base = "";
                    String potencia = "";
                    int j = index + 1;

                    while (j < temp.length() && (Character.isDigit(temp.charAt(j)) || temp.charAt(j) == '.')) {
                        potencia += temp.charAt(j);
                        j++;
                    }

                    j = index - 1;
                    while (j >= 0 && (Character.isDigit(temp.charAt(j)) || temp.charAt(j) == '.')) {
                        base = temp.charAt(j) + base;
                        j--;
                    }

                    //System.out.println(base+"^"+potencia);
                    //obtiene el valor de la potencia
                    double s_resultado = Math.pow(Double.parseDouble(base), Double.parseDouble(potencia));
                    //reemplaza base a la potencia por el real valor numerico
                    temp = temp.replace(base + "^" + potencia, String.format("%.2f", s_resultado));
                    System.out.println(temp);
                }

                //evalua la ecuacion
                x = (double) engine.eval(temp);
                System.out.println(String.format("%.2f", x));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "se ha presentado un error al aplicar la formula");
            System.out.println(e.getCause());
            System.out.println(e.getMessage());
        }
        return x;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorFunciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtG;
    private javax.swing.JTextField txtIteraciones;
    private javax.swing.JTextField txtIteracionesMedios;
    private javax.swing.JTextField txtIteraciones_GCL;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX_GCL;
    // End of variables declaration//GEN-END:variables
}
